/**
 * ============================================================
 * GLOBAL TRADE TYCOON - 17 LEVEL PROGRESSION SYSTEM
 * Struktur 17 Level Progresi Hirarkis dari Pedagang Kota
 * hingga Penguasa Rantai Pasok Dunia, lengkap dengan Skala Peta
 * Dinamis dan Landasan Prinsip Ilmu Ekonomi Global Trade.
 * ============================================================
 */

const TRADE_LEVELS = [
    // 🏙️ FASE I: TINGKAT LOKAL & DOMESTIK (LEVEL 1 - 4)
    {
        level: 1,
        title: 'Pedagang Pasar Kota Asal',
        phase: 'Fase I: Pasar Domestik',
        mapScale: 'CITY',
        mapName: 'Peta Kota Metropolis (Surabaya / Jakarta)',
        economicPrinciple: 'Hukum Permintaan & Penawaran Lokal (Alfred Marshall)',
        economicDesc: 'Mengoptimalkan marjin keuntungan dari perbedaan harga di pasar pinggiran vs pasar pusat.',
        badge: '🏪',
        desc: 'Membeli komoditas primer dari produsen pinggiran kota dan mendistribusikannya ke pasar induk kota asal.',
        unlockedCommodities: ['PALM_OIL_RAW', 'NICKEL_ORE'],
        targetProfit: 15000,
        targetVolume: 50, // ton
        requiredFleet: 'Truk Ringan Pickup',
        impactGoal: 'Ciptakan 25 lapangan kerja lokal di kota asal.',
        rewardCapital: 5000
    },
    {
        level: 2,
        title: 'Distributor Jalur Darat Antar-Kota',
        phase: 'Fase I: Pasar Domestik',
        mapScale: 'INTERCITY',
        mapName: 'Peta Koridor Jalur Pantura (Antar-Kota)',
        economicPrinciple: 'Model Gravitasi Spasial & Biaya Logistik (Jan Tinbergen)',
        economicDesc: 'Jarak tempuh dan kepadatan jalan mempengaruhi biaya transportasi riil per ton.',
        badge: '🚚',
        desc: 'Memperluas rute logistik ke kota-kota tetangga melalui jalur darat dengan armada truk pendingin.',
        unlockedCommodities: ['PALM_OIL_RAW', 'NICKEL_ORE', 'SOYBEAN'],
        targetProfit: 45000,
        targetVolume: 150,
        requiredFleet: 'Armada Truk Fuso Antar-Kota',
        impactGoal: 'Stabilkan harga komoditas pangan antar kota (Inflasi < 5%).',
        rewardCapital: 12000
    },
    {
        level: 3,
        title: 'Logistik Maritim Antar-Pulau',
        phase: 'Fase I: Pasar Domestik',
        mapScale: 'NATIONAL',
        mapName: 'Peta Maritim Kepulauan Nusantara (Antar-Pulau)',
        economicPrinciple: 'Teori Keunggulan Lokasi & Aglomerasi Maritim (Alfred Weber)',
        economicDesc: 'Menjembatani disparitas harga komoditas antara pulau produsen dan pulau konsumen.',
        badge: '⛴️',
        desc: 'Menyewa kapal feri dan kontainer feeder untuk menjembatani perdagangan antar pulau (Jawa - Sumatera - Kalimantan).',
        unlockedCommodities: ['PALM_OIL_RAW', 'NICKEL_ORE', 'SOYBEAN', 'IRON_ORE'],
        targetProfit: 120000,
        targetVolume: 400,
        requiredFleet: 'Kapal Kargo Feeder Domestik',
        impactGoal: 'Koneksikan 3 pelabuhan pulau untuk integrasi logistik nasional.',
        rewardCapital: 30000
    },
    {
        level: 4,
        title: 'Penguasa Hub Pergudangan Nasional',
        phase: 'Fase I: Pasar Domestik',
        mapScale: 'NATIONAL',
        mapName: 'Peta Jaringan Hub Logistik Nusantara',
        economicPrinciple: 'Keseimbangan Pasar & Cadangan Penyangga (Buffer Stock Theory)',
        economicDesc: 'Gudang modern mengendalikan fluktuasi harga musiman dan mencegah kelangkaan.',
        badge: '🏢',
        desc: 'Membangun jaringan pergudangan modern (Cold Storage & Silo) untuk mengamankan stok cadangan nasional.',
        unlockedCommodities: ['PALM_OIL_RAW', 'NICKEL_ORE', 'SOYBEAN', 'IRON_ORE', 'REFINED_STEEL'],
        targetProfit: 300000,
        targetVolume: 1000,
        requiredFleet: 'Jaringan Gudang Otomatis',
        impactGoal: 'Kontribusi penerimaan pajak nasional mencapai $50,000.',
        rewardCapital: 75000
    },

    // 🌏 FASE II: PENETRASI REGIONAL ASEAN & HILIRISASI (LEVEL 5 - 8)
    {
        level: 5,
        title: 'Eksportir Perdana Selat Malaka',
        phase: 'Fase II: Regional ASEAN',
        mapScale: 'REGIONAL_ASEAN',
        mapName: 'Peta Koridor Selat Malaka & Singapura',
        economicPrinciple: 'Keunggulan Komparatif Klasik (David Ricardo)',
        economicDesc: 'Spesialisasi pada komoditas dengan biaya peluang (opportunity cost) terendah.',
        badge: '🚢',
        desc: 'Memulai pengiriman ekspor komoditas primer ke pelabuhan tetangga (Singapura) dan meraih devisa ekspor.',
        unlockedCommodities: ['PALM_OIL_RAW', 'NICKEL_ORE', 'PETROCHEMICALS'],
        targetProfit: 750000,
        targetVolume: 2500,
        requiredFleet: 'Kapal Kontainer Regional',
        impactGoal: 'Hasilkan surplus neraca perdagangan $200,000 untuk Indonesia.',
        rewardCapital: 150000
    },
    {
        level: 6,
        title: 'Segitiga Perdagangan Malaka',
        phase: 'Fase II: Regional ASEAN',
        mapScale: 'REGIONAL_ASEAN',
        mapName: 'Peta Segitiga Perdagangan Malaka',
        economicPrinciple: 'Perjanjian Dagang Bebas & Tanpa Tarif (AFTA / Free Trade Area)',
        economicDesc: 'Tarif bea cukai 0% memaksimalkan surplus konsumen dan produsen regional.',
        badge: '⚓',
        desc: 'Menguasai jalur pelayaran tersibuk dunia dengan perdagangan timbal-balik bahan baku dan petrokimia.',
        unlockedCommodities: ['PALM_OIL_RAW', 'NICKEL_ORE', 'PETROCHEMICALS', 'REFINED_STEEL'],
        targetProfit: 1800000,
        targetVolume: 6000,
        requiredFleet: 'Armada Tongkang & Feeder',
        impactGoal: 'Ciptakan 500 lapangan kerja di pelabuhan transit.',
        rewardCapital: 350000
    },
    {
        level: 7,
        title: 'Integrasi Rantai Pasok ASEAN',
        phase: 'Fase II: Regional ASEAN',
        mapScale: 'REGIONAL_ASEAN',
        mapName: 'Peta Jaringan Rantai Pasok ASEAN',
        economicPrinciple: 'Teori Proporsi Faktor Produksi (Heckscher-Ohlin Model)',
        economicDesc: 'Negara kaya tenaga kerja mengekspor manufaktur, negara kaya lahan mengekspor komoditas.',
        badge: '🌏',
        desc: 'Menghubungkan rantai pasok mineral kritis, energi, dan komoditas pangan se-Asia Tenggara.',
        unlockedCommodities: ['PALM_OIL_RAW', 'NICKEL_ORE', 'LITHIUM_RAW', 'PETROCHEMICALS'],
        targetProfit: 4500000,
        targetVolume: 15000,
        requiredFleet: 'Kapal Curah Kering (Handymax)',
        impactGoal: 'Tingkatkan devisa ekspor regional dan serap 1,500 pekerja.',
        rewardCapital: 800000
    },
    {
        level: 8,
        title: 'Pabrik Pengolahan & Hilirisasi Pertama',
        phase: 'Fase II: Regional ASEAN',
        mapScale: 'REGIONAL_ASEAN',
        mapName: 'Peta Hilirisasi Industri ASEAN',
        economicPrinciple: 'Tangga Nilai Tambah & Kurva Senyum (Value-Added Smile Curve)',
        economicDesc: 'Mengolah bahan mentah menjadi intermediate goods melipatgandakan Terms of Trade.',
        badge: '🏭',
        desc: 'Membangun pabrik peleburan (Smelter) untuk mengolah bijih nikel dan lithium menjadi Sel Baterai bernilai tinggi.',
        unlockedCommodities: ['BATTERY_CELLS', 'REFINED_STEEL', 'PETROCHEMICALS'],
        targetProfit: 10000000,
        targetVolume: 35000,
        requiredFleet: 'Smelter & Pabrik Baterai Mandiri',
        impactGoal: 'Naikkan nilai tambah ekspor industri dalam negeri sebesar 300%.',
        rewardCapital: 1800000
    },

    // 🌐 FASE III: RANTAI PASOK GLOBAL LINTAS BENUA (LEVEL 9 - 13)
    {
        level: 9,
        title: 'Koridor Teknologi Asia Timur',
        phase: 'Fase III: Rantai Pasok Global',
        mapScale: 'GLOBAL',
        mapName: 'Peta Koridor Teknologi Asia Timur (China & Jepang)',
        economicPrinciple: 'Teori Berlian Daya Saing Nasional (Michael Porter’s Diamond Model)',
        economicDesc: 'Kemitraan rantai pasok antara klaster baterai Indonesia dan manufaktur maju Asia Timur.',
        badge: '💾',
        desc: 'Memasok baterai EV ke pabrik perakitan China dan mengimpor mikrochip presisi dari Tokyo (Jepang).',
        unlockedCommodities: ['BATTERY_CELLS', 'MICROCHIPS', 'SMARTPHONES'],
        targetProfit: 25000000,
        targetVolume: 80000,
        requiredFleet: 'Kapal Kontainer Panamax',
        impactGoal: 'Integrasikan rantai pasok chip semikonduktor Asia Timur.',
        rewardCapital: 4000000
    },
    {
        level: 10,
        title: 'Rute Energi Teluk Persia',
        phase: 'Fase III: Rantai Pasok Global',
        mapScale: 'GLOBAL',
        mapName: 'Peta Ketahanan Energi Teluk Persia & Arab',
        economicPrinciple: 'Elastisitas Permintaan & Keamanan Energi Global (Energy Inelasticity)',
        economicDesc: 'Mengamankan kontrak minyak mentah berbiaya rendah untuk industri kimia.',
        badge: '🛢️',
        desc: 'Mengamankan kontrak pasokan minyak mentah raksasa dari Arab Saudi untuk bahan baku industri kimia dunia.',
        unlockedCommodities: ['CRUDE_OIL', 'PETROCHEMICALS', 'BATTERY_CELLS'],
        targetProfit: 60000000,
        targetVolume: 180000,
        requiredFleet: 'Kapal Tanker Minyak Raksasa (VLCC)',
        impactGoal: 'Jamin ketahanan pasokan energi industri manufaktur global.',
        rewardCapital: 9000000
    },
    {
        level: 11,
        title: 'Jembatan Trans-Pasifik',
        phase: 'Fase III: Rantai Pasok Global',
        mapScale: 'GLOBAL',
        mapName: 'Peta Pelayaran Trans-Pasifik (Asia - Amerika)',
        economicPrinciple: 'Diferensiasi Produk & Teori Perdagangan Baru (Paul Krugman)',
        economicDesc: 'Konsumen AS membeli produk bernilai tinggi; skala pasar menurunkan biaya rata-rata.',
        badge: '🌉',
        desc: 'Membuka jalur pelayaran langsung Pasifik ke Port of Los Angeles (AS) untuk memasok barang jadi dan pesawat.',
        unlockedCommodities: ['ELECTRIC_VEHICLES', 'SMARTPHONES', 'AEROSPACE_PARTS'],
        targetProfit: 140000000,
        targetVolume: 400000,
        requiredFleet: 'Armada Trans-Pasifik Express',
        impactGoal: 'Buka akses pasar konsumen terbesar dunia senilai $50 Juta.',
        rewardCapital: 20000000
    },
    {
        level: 12,
        title: 'Rute Maritim Terusan Suez & Eropa',
        phase: 'Fase III: Rantai Pasok Global',
        mapScale: 'GLOBAL',
        mapName: 'Peta Euro-Asia Mega Route & Terusan Suez',
        economicPrinciple: 'Pajak Karbon Batas & Eksternalitas Lingkungan (EU CBAM & ESG)',
        economicDesc: 'Kepatuhan standar emisi rendah dan bebas deforestasi membuka pasar premium Eropa.',
        badge: '🏰',
        desc: 'Ekspansi ke Hamburg (Jerman) dan Basel (Swiss) dengan sertifikasi pasokan bebas deforestasi (ESG Standard).',
        unlockedCommodities: ['PRECISION_MOTORS', 'MEDICAL_INSTRUMENTS', 'ELECTRIC_VEHICLES'],
        targetProfit: 320000000,
        targetVolume: 900000,
        requiredFleet: 'Kapal Kargo Ultra Large (ULCV)',
        impactGoal: 'Pertahankan indeks ESG di atas 90 untuk lolos regulasi Uni Eropa.',
        rewardCapital: 45000000
    },
    {
        level: 13,
        title: 'Kepemilikan Armada Kapal Raksasa',
        phase: 'Fase III: Rantai Pasok Global',
        mapScale: 'GLOBAL',
        mapName: 'Peta Jaringan Armada Mandiri Global',
        economicPrinciple: 'Skala Ekonomis Internal & Integrasi Vertikal (Coase Transaction Cost)',
        economicDesc: 'Memiliki armada sendiri mengeliminasi marjin keuntungan pihak ketiga (freight margin).',
        badge: '👑',
        desc: 'Membeli lini pelayaran kapal kontainer sendiri dan armada kargo udara, mengeliminasi biaya logistik pihak ketiga.',
        unlockedCommodities: Object.keys(TRADE_COMMODITIES),
        targetProfit: 700000000,
        targetVolume: 2000000,
        requiredFleet: 'Lini Pelayaran Global Mandiri',
        impactGoal: 'Pangkas biaya logistik ekspor nasional hingga 35%.',
        rewardCapital: 100000000
    },

    // 🪐 FASE IV: HEGEMONI RANTAI PASOK DUNIA (LEVEL 14 - 17)
    {
        level: 14,
        title: 'Integrasi Belahan Bumi Selatan',
        phase: 'Fase IV: Hegemoni Dunia',
        mapScale: 'GLOBAL',
        mapName: 'Peta Global South Mineral & Agrikultur',
        economicPrinciple: 'Diversifikasi Portofolio Risiko Rantai Pasok (Markowitz Frontier)',
        economicDesc: 'Menggabungkan tambang Australia dan pangan Brazil menyeimbangkan guncangan geopolitik.',
        badge: '🌎',
        desc: 'Mengintegrasikan tambang bijih besi & pangan Brazil untuk mengamankan ketahanan pangan dan logam dunia.',
        unlockedCommodities: Object.keys(TRADE_COMMODITIES),
        targetProfit: 1500000000,
        targetVolume: 5000000,
        requiredFleet: 'Valemax Ore Carrier',
        impactGoal: 'Stabilkan harga pangan dunia dengan pasokan 1 Juta ton kedelai.',
        rewardCapital: 250000000
    },
    {
        level: 15,
        title: 'Otomasi AI & Pelabuhan Pintar JIT',
        phase: 'Fase IV: Hegemoni Dunia',
        mapScale: 'GLOBAL',
        mapName: 'Peta Logistik Otonom & AI JIT Global',
        economicPrinciple: 'Manajemen Rantai Pasok Ramping (Toyota Lean & Just-In-Time)',
        economicDesc: 'Meminimalkan biaya simpan pergudangan (holding cost) mendekati nol.',
        badge: '🤖',
        desc: 'Menerapkan algoritma AI peramalan rantai pasok Just-In-Time, memangkas waktu tunggu pelabuhan menjadi 0 hari.',
        unlockedCommodities: Object.keys(TRADE_COMMODITIES),
        targetProfit: 3500000000,
        targetVolume: 12000000,
        requiredFleet: 'Sistem Logistik Otonom AI',
        impactGoal: 'Serap 50,000 tenaga kerja berketerampilan tinggi di seluruh dunia.',
        rewardCapital: 600000000
    },
    {
        level: 16,
        title: 'Sindikat & Pengendali Kartel Komoditas',
        phase: 'Fase IV: Hegemoni Dunia',
        mapScale: 'GLOBAL',
        mapName: 'Peta Pengendali Bursa Komoditas Dunia',
        economicPrinciple: 'Teori Kekuatan Pasar Oligopoli & Kartel (Cournot & Bertrand Duopoly)',
        economicDesc: 'Kapasitas menentukan volume pasokan global memberi kekuatan penetapan harga pasar.',
        badge: '⚖️',
        desc: 'Menguasai >25% sirkulasi baterai EV dan semikonduktor dunia, mampu menentukan harga acuan kontrak berjangka.',
        unlockedCommodities: Object.keys(TRADE_COMMODITIES),
        targetProfit: 8000000000,
        targetVolume: 30000000,
        requiredFleet: 'Konsorsium Perdagangan Global',
        impactGoal: 'Kontribusi penerimaan pajak global melampaui $1 Miliar.',
        rewardCapital: 1500000000
    },
    {
        level: 17,
        title: 'Penguasa Rantai Pasok Dunia (World Trade Titan)',
        phase: 'Fase IV: Hegemoni Dunia',
        mapScale: 'GLOBAL',
        mapName: 'Peta Hegemoni Rantai Pasok Global (Planet Bumi)',
        economicPrinciple: 'Teori Stabilitas Hegemonik (Kindleberger Hegemonic Stability Theory)',
        economicDesc: 'Menjaga keterbukaan jalur maritim, stabilitas harga pangan, dan pasokan energi seluruh planet.',
        badge: '🪐',
        desc: 'Menopang lebih dari 50% arus barang strategis planet Bumi. Stabilitas ekonomi dan industri dunia berada di tangan Anda!',
        unlockedCommodities: Object.keys(TRADE_COMMODITIES),
        targetProfit: 20000000000,
        targetVolume: 80000000,
        requiredFleet: 'Hegemoni Rantai Pasok Global',
        impactGoal: 'Ciptakan 200,000 lapangan kerja dan capai status Net-Zero Green Supply Chain.',
        rewardCapital: 5000000000
    }
];
